[build]
  command = "npm run build" # Ou o comando de build do seu projeto
  publish = "public"        # Caminho do diretório de saída do build

[[plugins]]
  package = "./plugins/netlify-plugin-generate-links"