name: Deploy Site

on:
  workflow_dispatch:

jobs:
  deploy_site:
    runs-on: ubuntu-latest

    steps:
    - name: Check out o código
      uses: actions/checkout@v3

    - name: Configurar Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22'

    - name: Instalar dependências
      run: npm install

    - name: Instalar Netlify CLI
      run: npm install -g netlify-cli@19.0.3

    - name: Definir variáveis de ambiente
      run: echo "NODE_ENV=production" >> $GITHUB_ENV  # Definir NODE_ENV como 'production'

    - name: Executar o script main.js
      run: node src/main.js  # Executa o script para gerar o HTML
      env:
        GOOGLE_SHEET_ID: ${{ secrets.GOOGLE_SHEET_ID }}
        GOOGLE_CREDENTIALS_BASE64: ${{ secrets.GOOGLE_CREDENTIALS_BASE64 }}
        API_BASE_URL: ${{ secrets.API_BASE_URL }}
        API_KEY: ${{ secrets.API_KEY }}
        NODE_ENV: ${{ env.NODE_ENV }}

    - name: Realizar deploy no Netlify
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_ACCESS_TOKEN }}
      run: |
        # Linka o diretório ao site Netlify usando o ID
        netlify link --id ${{ secrets.NETLIFY_SITE_ID }}
        
        # Realiza o deploy no Netlify
        netlify deploy --prod --dir=public
