name: Generate Index on Redirects Change 

on:
  push:
    paths:
      - _redirects # Apenas dispara se _redirects generate-index forem alterados
      - generate-index.js

permissions:
  contents: write # Permissão para fazer commit e push

jobs:
  generate-index:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Generate index.html
      run: node generate-index.js # Roda o script para gerar o index.html

    - name: Commit changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --local user.name "GitHub Actions Bot"
        git config --local user.email "actions@github.com"
        git add index.html
        git commit -m "Atualiza index.html baseado no _redirects"
        git push
